
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: admin

development:
  <<: *default
  database: sistema_login_base_development

test:
  <<: *default
  database: sistema_login_base_test

production:
  <<: *default
  database: sistema_login_base_production
  username: sistema_login_base
  password: <%= ENV["SISTEMA_LOGIN_BASE_DATABASE_PASSWORD"] %>
